In [1]:
#READ THE DATA AND CREATE ADJACENCY MATRIX

import numpy as np
import pandas as pd
p_data = open("/Users/joshem/PhD Research/Data/citeseer-doc/citeseer.cites")


# Create a list from the data
myls=list(p_data)

# Remove the new line symbole from the list
mylist = [line.rstrip('\n') for line in myls]
#print(mylist)
#print(graph_ind)
#print(graph_level)

p_data.close()
mynode=[]
i=0
for d in mylist:
    d=mylist[i].split("\t")
    mynode.append(d[0])
    mynode.append(d[1])
    i=i+1
#print(mynode)
node_ID1=np.unique(mynode)
node_ID2=list(node_ID1)
#print(node_ID2)
n=len(node_ID2)
print(n)
from natsort import natsorted, ns
node_ID=natsorted(node_ID2)
#print(node_ID)
A=np.zeros((n,n))
i=0
for d in mylist:
    d=mylist[i].split("\t")
    A[node_ID.index(d[0])][node_ID.index(d[1])]=1
    i=i+1;
print(" The adjacency Matrix")
print("=======================")
print(A)

3312
 The adjacency Matrix
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [23]:
#READ THE NODE FEATURE

import os
data_dir = os.path.expanduser("/Users/joshem/PhD Research/Data/citeseer-doc")

feature_names = ["w_{}".format(ii) for ii in range(3703)]
column_names = ["ID"]+ feature_names + ["subject"]
node_data = pd.read_csv(os.path.join(data_dir, "citeseer.content"), sep='\t', header=None, names=column_names)
node_data.head()

/var/folders/k8/fv2pzvcn5p77dgds_c16lsl80000gn/T/ipykernel_5008/2957520849.py:6: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  node_data = pd.read_csv(os.path.join(data_dir, "citeseer.content"), sep='\t', header=None, names=column_names)


ID  w_0  w_1  w_2  w_3  w_4  w_5  w_6  w_7  w_8  ...  w_3694  w_3695  \
0  100157    0    0    0    0    0    0    0    0    0  ...       0       0   
1  100598    0    0    0    0    0    0    0    0    0  ...       0       0   
2  105684    0    1    0    0    0    0    0    0    0  ...       0       0   
3   11099    0    0    0    0    0    0    0    0    0  ...       0       0   
4  114091    0    0    0    0    0    0    0    0    0  ...       0       0   

   w_3696  w_3697  w_3698  w_3699  w_3700  w_3701  w_3702  subject  
0       0       0       0       0       0       0       0   Agents  
1       0       0       0       0       0       0       0       IR  
2       0       0       0       0       0       0       0   Agents  
3       0       0       0       0       0       0       0       DB  
4       0       0       0       0       0       0       0       AI  

[5 rows x 3705 columns]

In [24]:
DataS=node_data.replace({'subject': {'Agents':0 , 'AI': 1,'DB':2,'IR':3 , 'ML': 4,'HCI':5}})
# Agents==0
#		AI==1
#		DB==2
#		IR==3
#		ML==4
#		HCI==5

DataS.head()

ID  w_0  w_1  w_2  w_3  w_4  w_5  w_6  w_7  w_8  ...  w_3694  w_3695  \
0  100157    0    0    0    0    0    0    0    0    0  ...       0       0   
1  100598    0    0    0    0    0    0    0    0    0  ...       0       0   
2  105684    0    1    0    0    0    0    0    0    0  ...       0       0   
3   11099    0    0    0    0    0    0    0    0    0  ...       0       0   
4  114091    0    0    0    0    0    0    0    0    0  ...       0       0   

   w_3696  w_3697  w_3698  w_3699  w_3700  w_3701  w_3702  subject  
0       0       0       0       0       0       0       0        0  
1       0       0       0       0       0       0       0        3  
2       0       0       0       0       0       0       0        0  
3       0       0       0       0       0       0       0        2  
4       0       0       0       0       0       0       0        1  

[5 rows x 3705 columns]

In [26]:
#SORT THE NODE FEATURE ACCORDING TO ID

from natsort import index_natsorted, order_by_index

Data = DataS.reindex(index=order_by_index(DataS.index, index_natsorted(Data['ID'], reverse=False)))
#Data = Data.reset_index(drop=True)
Data.head()

ID  w_0  w_1  w_2  w_3  w_4  w_5  w_6  w_7  w_8  ...  w_3694  w_3695  \
29     210    0    0    0    0    0    0    0    0    0  ...       0       0   
1380   845    0    0    0    0    0    0    0    0    0  ...       0       0   
2509   940    0    0    0    0    0    0    0    0    0  ...       0       0   
2206  1529    0    0    0    0    0    0    0    0    0  ...       0       0   
2210  1625    0    0    0    0    0    0    0    0    0  ...       0       0   

      w_3696  w_3697  w_3698  w_3699  w_3700  w_3701  w_3702  subject  
29         0       0       0       0       0       0       0        4  
1380       0       0       0       0       0       0       0        4  
2509       0       0       0       0       0       0       0        3  
2206       0       0       0       0       0       0       0        2  
2210       0       0       0       0       0       0       0        4  

[5 rows x 3705 columns]

In [29]:
#RANDOMLY CHOOSE 1000 NODE FOR TEST DATA

catagories=Data['subject'].to_numpy()
print(catagories)
import random
p=random.sample(range(3312), 1000)
#print(p)
q=[]
for i in range(n):
    if i not in p:
        q.append(i)

[4 4 3 ... 4 0 0]


In [31]:
#LABLE THE UNKNOWN/TEST NODE AS 6 AND PLACE CLASS TO THE DIAGONAL OF ADJACENCY MATRIX

class_60=np.array(catagories)
for d in p:
    class_60[d]=6
print(class_60)
for i in range(n):
    A[i][i]=class_60[i]
print(A)

[4 6 3 ... 6 0 0]
[[4. 0. 0. ... 0. 0. 0.]
 [0. 6. 0. ... 0. 0. 0.]
 [0. 0. 3. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 6. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
def CountX(lst,x):
    return(lst.count(x))
#CREARTE AN ARRAY OF 1 AND 2 HOP NBD FOR EACH NODE

Node_class=[0,1,2,3,4,5]
F_vec=[]
for i in range(n):
    node_F=[]
    list_out=[]
    list_In=[]
    S_nbd_out=[]
    S_nbd_in=[]
    for j in range(n):
        if A[i][j]==1 and i!=j:
            list_out.append(A[j][j])
            for k in range(n):
                if A[j][k]==1 and k!=j:
                    S_nbd_out.append(A[k][k])
        if A[j][i]==1 and i!=j:
            list_In.append(A[j][j])
            for k in range(n):
                if A[k][j]==1 and k!=j:
                    S_nbd_in.append(A[k][k])
     # COUNT FOR EACH CLASS           
    for d in Node_class:
        node_F.append(CountX(list_out,d))
        node_F.append(CountX(list_In,d))
    for d in Node_class:
        node_F.append(CountX(S_nbd_out,d))
        node_F.append(CountX(S_nbd_in,d))
    F_vec.append(node_F)

In [32]:
x =np.array(F_vec)
k=24
feature=["a_0","b_0"]
for i in range(1,k-1,2):
    feature.append("a_{}".format(int((i+1)/2)))
    feature.append("b_{}".format(int((i+1)/2)))

    
data = pd.DataFrame(x,columns=feature)
data.insert(loc=k,column='Class',value=Data['subject'].to_numpy())
data.head()

a_0  b_0  a_1  b_1  a_2  b_2  a_3  b_3  a_4  b_4  ...  b_7  a_8  b_8  a_9  \
0    0    1    0    0    0    0    0    0    1    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    4    0  ...    0    0    0    0   
2    0    0    0    0    1    0    2    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    2    0  ...    0    0    0    0   
4    0    0    0    0    1    0    0    0    1    1  ...    0    0    0    1   

   b_9  a_10  b_10  a_11  b_11  Class  
0    0     1     0     1     0      4  
1    0     4     0     0     0      4  
2    0     0     0     0     0      3  
3    0     2     0     0     0      2  
4    0     1     1     0     0      4  

[5 rows x 25 columns]

In [33]:
#SEPERATE CLUSTER OF DATA FOR EACH CLASS

Data_0=Data.loc[Data['subject'] == 0]
Data_1=Data.loc[Data['subject'] == 1]
Data_2=Data.loc[Data['subject'] == 2]
Data_3=Data.loc[Data['subject'] == 3]
Data_4=Data.loc[Data['subject'] == 4]
Data_5=Data.loc[Data['subject'] == 5]
#REPRESENTATIVE OF EACH CLASS USING INCLUSIVE SETTING
Basis_0=[]
Basis_1=[]
Basis_2=[]
Basis_3=[]
Basis_4=[]
Basis_5=[]
for i in range(3703):
    W="w_{}".format(i)
    Basis_0.append(max(Data_0[W].to_numpy()))
    Basis_1.append(max(Data_1[W].to_numpy()))
    Basis_2.append(max(Data_2[W].to_numpy()))
    Basis_3.append(max(Data_3[W].to_numpy()))
    Basis_4.append(max(Data_4[W].to_numpy()))
    Basis_5.append(max(Data_5[W].to_numpy()))
#print(Basis_0)
#W1=Data_0['w_0'].to_numpy()
#print(max(W1))
count0=0
count1=0
for i in range(3703):
    if Basis_0[i]==1:
        count1=count1+1
    else:
        count0=count0+1
print(count0)
print(count1)

1199
2504


In [34]:
#REPRESENTATIVE USING SELECTIVE SETTING
SBasis_0=[]
SBasis_1=[]
SBasis_2=[]
SBasis_3=[]
SBasis_4=[]
SBasis_5=[]
#for i in range(14):
 #   W="w_{}".format(i)
  #  print(list(Data_0[W].to_numpy()).count(1))
for i in range(3703):
    W="w_{}".format(i)
    if list(Data_0[W].to_numpy()).count(1)>=int(len(Data_0.index)*0.1):
        SBasis_0.append(1)
    else:
        SBasis_0.append(0) 
    if list(Data_1[W].to_numpy()).count(1)>=int(len(Data_1.index)*0.1):
        SBasis_1.append(1)
    else:
        SBasis_1.append(0)
    if list(Data_2[W].to_numpy()).count(1)>=int(len(Data_2.index)*0.1):
        SBasis_2.append(1)
    else:
        SBasis_2.append(0)
    if list(Data_3[W].to_numpy()).count(1)>=int(len(Data_3.index)*0.1):
        SBasis_3.append(1)
    else:
        SBasis_3.append(0)
    if list(Data_4[W].to_numpy()).count(1)>=int(len(Data_4.index)*0.1):
        SBasis_4.append(1)
    else:
        SBasis_4.append(0)
    if list(Data_5[W].to_numpy()).count(1)>=int(len(Data_5.index)*0.1):
        SBasis_5.append(1)
    else:
        SBasis_5.append(0)
#W1=Data_0['w_0'].to_numpy()
#print(max(W1))
count0=0
count1=0
for i in range(3703):
    if SBasis_0[i]==1:
        count1=count1+1
    else:
        count0=count0+1
print(count0)
print(count1)

3663
40


In [27]:
IdS=list(DataS['ID'].to_numpy())
Id=list(Data['ID'].to_numpy())
#print(Id)
#print(IdS)
print(IdS.index(Id[1]))

1380


In [35]:
#CREATE FEATURE VECTOR USING SIMILARITY MEASURE WITH REPRESENTATIVE OF EACH CLASS(INCLUSIVE)

Fec=[]
for i in range(3312):
    vec=[]
    f=Data.loc[IdS.index(Id[i]), feature_names].values.flatten().tolist()
    count=0
    count1=0
    count2=0
    count3=0
    count4=0
    count5=0
    for j in range(3703):
        if f[j]==1 and Basis_0[j]==1:
            count=count+1;
        if f[j]==1 and Basis_1[j]==1:
            count1=count1+1;
        if f[j]==1 and Basis_2[j]==1:
            count2=count2+1;
        if f[j]==1 and Basis_3[j]==1:
            count3=count3+1;
        if f[j]==1 and Basis_4[j]==1:
            count4=count4+1;
        if f[j]==1 and Basis_5[j]==1:
            count5=count5+1;
    vec.append(count)
    vec.append(count1)
    vec.append(count2)
    vec.append(count3)
    vec.append(count4)
    vec.append(count5)
    #print(f)
    f.clear()
    Fec.append(vec)
print(Fec)

[[37, 30, 32, 32, 37, 34], [32, 32, 34, 32, 36, 30], [27, 28, 27, 29, 29, 27], [29, 28, 34, 30, 31, 30], [26, 25, 25, 25, 27, 22], [24, 21, 24, 26, 27, 24], [26, 24, 27, 31, 26, 24], [37, 33, 43, 40, 33, 36], [26, 25, 33, 32, 34, 27], [34, 35, 31, 32, 33, 33], [41, 45, 32, 31, 42, 38], [31, 27, 31, 36, 37, 30], [36, 38, 42, 43, 43, 40], [37, 36, 36, 39, 40, 34], [30, 29, 37, 36, 34, 34], [34, 33, 36, 33, 31, 32], [25, 26, 24, 27, 25, 24], [25, 30, 30, 24, 26, 25], [28, 29, 32, 28, 33, 29], [36, 33, 37, 36, 38, 32], [22, 23, 22, 24, 28, 25], [38, 30, 41, 32, 32, 30], [25, 23, 23, 31, 27, 24], [34, 33, 37, 40, 40, 35], [31, 32, 29, 30, 31, 29], [28, 26, 25, 26, 27, 30], [27, 29, 30, 31, 37, 28], [23, 21, 23, 25, 24, 22], [34, 38, 38, 34, 35, 31], [25, 25, 27, 29, 29, 25], [32, 29, 29, 33, 35, 28], [21, 24, 25, 21, 26, 19], [30, 30, 33, 34, 34, 32], [38, 33, 30, 36, 33, 34], [38, 35, 35, 37, 34, 39], [26, 27, 25, 28, 28, 23], [35, 35, 35, 39, 38, 30], [32, 28, 38, 41, 41, 32], [38, 36, 44

In [36]:
#CREATE FEATURE VECTOR USING SIMILARITY MEASURE WITH REPRESENTATIVE OF EACH CLASS(EXCLUSIVE)
SFec=[]
for i in range(3312):
    Svec=[]
    f=Data.loc[IdS.index(Id[i]), feature_names].values.flatten().tolist()
    count=0
    count1=0
    count2=0
    count3=0
    count4=0
    count5=0
    for j in range(3703):
        if f[j]==1 and SBasis_0[j]==1:
            count=count+1;
        if f[j]==1 and SBasis_1[j]==1:
            count1=count1+1;
        if f[j]==1 and SBasis_2[j]==1:
            count2=count2+1;
        if f[j]==1 and SBasis_3[j]==1:
            count3=count3+1;
        if f[j]==1 and SBasis_4[j]==1:
            count4=count4+1;
        if f[j]==1 and SBasis_5[j]==1:
            count5=count5+1;
    Svec.append(count)
    Svec.append(count1)
    Svec.append(count2)
    Svec.append(count3)
    Svec.append(count4)
    Svec.append(count5)

    #print(f)
    f.clear()
    SFec.append(Svec)
print(SFec)

[[4, 6, 3, 4, 7, 6], [5, 7, 5, 5, 9, 4], [3, 6, 6, 12, 9, 3], [7, 10, 8, 9, 11, 7], [5, 11, 6, 7, 12, 5], [6, 6, 7, 6, 7, 8], [3, 3, 4, 8, 3, 3], [7, 8, 10, 11, 7, 6], [2, 4, 4, 8, 6, 3], [8, 9, 7, 6, 7, 7], [7, 7, 4, 6, 4, 5], [2, 2, 2, 2, 3, 1], [5, 7, 10, 12, 8, 5], [5, 7, 8, 8, 10, 6], [5, 4, 9, 7, 6, 4], [8, 5, 9, 6, 7, 5], [4, 3, 5, 3, 2, 2], [2, 6, 3, 1, 3, 1], [6, 7, 6, 9, 9, 6], [4, 5, 7, 8, 8, 2], [3, 4, 2, 3, 6, 2], [3, 6, 7, 3, 6, 2], [2, 4, 4, 8, 5, 3], [4, 4, 2, 6, 4, 0], [8, 9, 9, 9, 8, 7], [5, 3, 1, 3, 2, 7], [4, 5, 7, 4, 7, 5], [6, 4, 5, 4, 4, 4], [3, 5, 6, 4, 5, 2], [1, 3, 3, 5, 4, 0], [0, 2, 0, 0, 3, 0], [2, 2, 1, 1, 2, 2], [4, 4, 3, 3, 3, 2], [9, 7, 5, 4, 6, 5], [10, 9, 8, 7, 9, 8], [2, 4, 1, 6, 6, 0], [4, 3, 5, 12, 3, 3], [4, 7, 5, 10, 7, 5], [4, 4, 9, 4, 7, 5], [4, 5, 4, 6, 4, 4], [8, 2, 3, 3, 1, 5], [3, 2, 3, 3, 3, 1], [1, 3, 1, 4, 4, 1], [2, 3, 4, 4, 3, 0], [6, 8, 4, 4, 6, 5], [3, 4, 4, 4, 2, 2], [5, 3, 3, 2, 2, 3], [2, 7, 2, 4, 7, 3], [6, 6, 5, 7, 6, 4], [2, 4,

In [39]:
y =np.array(Fec)
data1=pd.DataFrame({"I_0":y[:,0]})
for i in range(5):
    data1.insert(loc=i+1, column="I_{}".format(i+1), value=y[:,i+1])
#data1.insert(loc=6,column='Class',value=Data['subject'].to_numpy())
data1.head()

I_0  I_1  I_2  I_3  I_4  I_5
0   37   30   32   32   37   34
1   32   32   34   32   36   30
2   27   28   27   29   29   27
3   29   28   34   30   31   30
4   26   25   25   25   27   22

In [40]:
z =np.array(SFec)
data2=pd.DataFrame({"S_0":z[:,0]})
for i in range(5):
    data2.insert(loc=i+1, column="S_{}".format(i+1), value=z[:,i+1])
#data2.insert(loc=7,column='Class',value=Data['subject'].to_numpy())
data2.head()

S_0  S_1  S_2  S_3  S_4  S_5
0    4    6    3    4    7    6
1    5    7    5    5    9    4
2    3    6    6   12    9    3
3    7   10    8    9   11    7
4    5   11    6    7   12    5

In [41]:
#FINAL FEATURE VECTOR
result = pd.concat([data1,data2,data], axis=1)
result.head()

I_0  I_1  I_2  I_3  I_4  I_5  S_0  S_1  S_2  S_3  ...  b_7  a_8  b_8  a_9  \
0   37   30   32   32   37   34    4    6    3    4  ...    0    0    0    0   
1   32   32   34   32   36   30    5    7    5    5  ...    0    0    0    0   
2   27   28   27   29   29   27    3    6    6   12  ...    0    0    0    0   
3   29   28   34   30   31   30    7   10    8    9  ...    0    0    0    0   
4   26   25   25   25   27   22    5   11    6    7  ...    0    0    0    1   

   b_9  a_10  b_10  a_11  b_11  Class  
0    0     1     0     1     0      4  
1    0     4     0     0     0      4  
2    0     0     0     0     0      3  
3    0     2     0     0     0      2  
4    0     1     1     0     0      4  

[5 rows x 37 columns]

In [42]:
k=24
feature=["a_0","b_0"]
for i in range(1,k-1,2):
    feature.append("a_{}".format(int((i+1)/2)))
    feature.append("b_{}".format(int((i+1)/2)))

for i in range(6):
    feature.append("I_{}".format(i))
for i in range(6):
    feature.append("S_{}".format(i))
    
    
X=result[feature] # Features
y=result['Class']  # Labels
X_train=X.iloc[q]
X_test=X.iloc[p]
y_train=y.iloc[q]
y_test=y.iloc[p]

from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(X_train)  
X_train = scaler.transform(X_train)  
# apply same transformation to test data
X_test = scaler.transform(X_test)  

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(700,), random_state=1,max_iter=10000, warm_start=True)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100,"%")

Accuracy: 90.7 %
