In [1]:
import tensorflow as tf

In [3]:
import pandas as pd
import numpy as np
import ogb
from ogb.nodeproppred import NodePropPredDataset 
from torch_geometric.data import DataLoader
#H:\\PhD Research\Data\PROTEINS\PROTEINS_node_attributes.txt
# Download and process data at './dataset/ogbg_molhiv/'
dataset = NodePropPredDataset(name = "ogbn-mag")
split_idx = dataset.get_idx_split()
train_idx, valid_idx, test_idx = split_idx["train"], split_idx["valid"], split_idx["test"]
graph = dataset[0] # pyg graph object

Downloaded 0.40 GB: 100%|██████████| 413/413 [01:45<00:00,  3.91it/s]


Extracting dataset/mag.zip
Loading necessary files...
This might take a while.
Processing graphs...


100%|██████████| 1/1 [00:00<00:00, 9489.38it/s]

Saving...


In [4]:
D=graph[0]

In [5]:
Class=graph[1]
Cla=Class['paper']
Node_Class=Cla[:,0]
df1 = pd.DataFrame(Node_Class,columns=["Class"])
#df1.head()
feature_names = ["w_{}".format(ii) for ii in range(128)]
#print(feature_names)
Node_Fec=list(D['node_feat_dict']['paper'])
df2 = pd.DataFrame(Node_Fec,columns=feature_names)
df2.head()

w_0       w_1       w_2       w_3       w_4       w_5       w_6  \
0 -0.095379  0.040758 -0.210948 -0.064362 -0.225940 -0.002323 -0.555826   
1 -0.151047 -0.107315 -0.221964 -0.034725  0.010814 -0.009673 -0.434323   
2 -0.114799 -0.175982 -0.260556  0.011920 -0.129273 -0.044518 -0.345423   
3  0.004506  0.042368 -0.178465 -0.138479 -0.138268  0.024902 -0.438153   
4 -0.094474 -0.080044 -0.222468 -0.158952 -0.024708  0.004351 -0.463666   

        w_7       w_8       w_9  ...     w_118     w_119     w_120     w_121  \
0 -0.352909  0.040634 -0.195226  ...  0.146386 -0.378653 -0.328871 -0.136878   
1 -0.461733  0.112732  0.091751  ...  0.047749 -0.065133 -0.208891 -0.366014   
2 -0.378261 -0.088449 -0.091060  ...  0.047763 -0.394512 -0.238776  0.080928   
3 -0.450127  0.066984 -0.017753  ...  0.116500 -0.255289 -0.278228 -0.081235   
4 -0.344648 -0.101808 -0.012426  ... -0.117917 -0.139355 -0.228969 -0.062332   

      w_122     w_123     w_124     w_125     w_126     w_127  
0 -0.007779 -0.157634 -0.069693  0.061569 -0.027663 -0.133832  
1 -0.045869 -0.297474  0.056755  0.345754 -0.027737 -0.218527  
2  0.057844 -0.205098 -0.067513  0.173058 -0.156445 -0.277954  
3  0.251969 -0.066206  0.095656  0.282228  0.016337 -0.212731  
4  0.132850 -0.269122  0.024864  0.288779 -0.186985 -0.205087  

[5 rows x 128 columns]

In [6]:
Data=pd.concat([df1, df2],axis=1)
Data.head()

Class       w_0       w_1       w_2       w_3       w_4       w_5  \
0    246 -0.095379  0.040758 -0.210948 -0.064362 -0.225940 -0.002323   
1    131 -0.151047 -0.107315 -0.221964 -0.034725  0.010814 -0.009673   
2    189 -0.114799 -0.175982 -0.260556  0.011920 -0.129273 -0.044518   
3    131  0.004506  0.042368 -0.178465 -0.138479 -0.138268  0.024902   
4     95 -0.094474 -0.080044 -0.222468 -0.158952 -0.024708  0.004351   

        w_6       w_7       w_8  ...     w_118     w_119     w_120     w_121  \
0 -0.555826 -0.352909  0.040634  ...  0.146386 -0.378653 -0.328871 -0.136878   
1 -0.434323 -0.461733  0.112732  ...  0.047749 -0.065133 -0.208891 -0.366014   
2 -0.345423 -0.378261 -0.088449  ...  0.047763 -0.394512 -0.238776  0.080928   
3 -0.438153 -0.450127  0.066984  ...  0.116500 -0.255289 -0.278228 -0.081235   
4 -0.463666 -0.344648 -0.101808  ... -0.117917 -0.139355 -0.228969 -0.062332   

      w_122     w_123     w_124     w_125     w_126     w_127  
0 -0.007779 -0.157634 -0.069693  0.061569 -0.027663 -0.133832  
1 -0.045869 -0.297474  0.056755  0.345754 -0.027737 -0.218527  
2  0.057844 -0.205098 -0.067513  0.173058 -0.156445 -0.277954  
3  0.251969 -0.066206  0.095656  0.282228  0.016337 -0.212731  
4  0.132850 -0.269122  0.024864  0.288779 -0.186985 -0.205087  

[5 rows x 129 columns]

In [7]:
Node_Year=D['node_year']['paper']
Node_Year_list=list(Node_Year[:,0])

E=D['edge_index_dict'][('paper', 'cites', 'paper')]
EdgeL=E[0]
EdgeR=E[1]
print(EdgeL)
print(EdgeR)
print(np.unique(Node_Year_list))

Node_Year_list.index(2019)
list_size = len(Node_Year_list)
NIndex_19=[]
# declare for loop
for itr in range(list_size):
 
      # check the condition
    if(Node_Year_list[itr] == 2019):
        NIndex_19.append(itr)
 
          # print the indices
print(len(NIndex_19))

[     0      0      0 ... 736388 736388 736388]
[    88  27449 121051 ... 421711 427339 439864]
[2010 2011 2012 2013 2014 2015 2016 2017 2018 2019]
41939


In [11]:
N_class_train=Node_Class
for d in NIndex_19:
    N_class_train[d]=349
print(np.unique(N_class_train))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [16]:
def CountX(lst,x):
    return(lst.count(x))

Node_class=list(range(350))
F_vec=[]
n=736389
for i in range(n):
    print("\r Processing file {} ({}%)".format(i, 100 * i //n), end='', flush=True)
    node_F=[]
    list_out=[]
    list_In=[]
    #S_nbd_out=[]
    #S_nbd_in=[]
    indx=np.where(EdgeL==i)
    indxIn=np.where(EdgeR==i)
    #print(indx)
    for j in indx[0]:
        list_out.append(N_class_train[EdgeR[j]])
   # indx[0].clear()
    for k in indxIn[0]:
        list_In.append(N_class_train[EdgeL[k]])
   # indxIn[0].clear()

                
                
    for d in Node_class:
        node_F.append(CountX(list_out,d))
        node_F.append(CountX(list_In,d))
    F_vec.append(node_F)

 Processing file 736388 (99%)

In [17]:
n=736388

node_F=[]
list_out=[]
list_In=[]
    #S_nbd_out=[]
    #S_nbd_in=[]
indx=np.where(EdgeL==n+1)
indxIn=np.where(EdgeR==n+1)
    #print(indx)
for j in indx[0]:
    list_out.append(N_class_train[EdgeR[j]])
   # indx[0].clear()
for k in indxIn[0]:
    list_In.append(N_class_train[EdgeL[k]])
   # indxIn[0].clear()

                
for d in Node_class:
    node_F.append(CountX(list_out,d))
    node_F.append(CountX(list_In,d))
F_vec.append(node_F)

In [29]:
del F_vec[-1]
print(len(F_vec))
print(len(Node_Class))

736389
736389


In [30]:
feature=['0']
for i in range(1,700):
    feature.append("{}".format(i))
data = pd.DataFrame(F_vec, columns =feature) 
data.insert(loc=700,column='Class',value=Node_Class)
data.head()

0  1  2  3  4  5  6  7  8  9  ...  691  692  693  694  695  696  697  698  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   699  Class  
0    0    246  
1    0    131  
2    0    189  
3    0    131  
4    0     95  

[5 rows x 701 columns]

In [31]:
compression_opts = dict(method='zip',
                        archive_name='Feature_1it_nbd_mag.csv')  
data.to_csv('Feature_1it_nbd_mag.zip', index=True,
          compression=compression_opts) 

In [32]:
result=pd.concat([data, df2],axis=1)
result.head()

0  1  2  3  4  5  6  7  8  9  ...     w_118     w_119     w_120     w_121  \
0  0  0  0  0  0  0  0  0  0  0  ...  0.146386 -0.378653 -0.328871 -0.136878   
1  0  0  0  0  0  0  0  0  0  0  ...  0.047749 -0.065133 -0.208891 -0.366014   
2  0  0  0  0  0  0  0  0  0  0  ...  0.047763 -0.394512 -0.238776  0.080928   
3  0  0  0  0  0  0  0  0  0  0  ...  0.116500 -0.255289 -0.278228 -0.081235   
4  0  0  0  0  0  0  0  0  0  0  ... -0.117917 -0.139355 -0.228969 -0.062332   

      w_122     w_123     w_124     w_125     w_126     w_127  
0 -0.007779 -0.157634 -0.069693  0.061569 -0.027663 -0.133832  
1 -0.045869 -0.297474  0.056755  0.345754 -0.027737 -0.218527  
2  0.057844 -0.205098 -0.067513  0.173058 -0.156445 -0.277954  
3  0.251969 -0.066206  0.095656  0.282228  0.016337 -0.212731  
4  0.132850 -0.269122  0.024864  0.288779 -0.186985 -0.205087  

[5 rows x 829 columns]

In [33]:
feature=['0']
for i in range(1,700):
    feature.append("{}".format(i))
for i in range(128):
    feature.append("w_{}".format(i))

X=result[feature] # Features
y=result['Class']  # Labels
X_train=X.iloc[list(train_idx['paper'])+list(valid_idx['paper'])]
X_test=X.iloc[test_idx['paper']]
y_train=y.iloc[list(train_idx['paper'])+list(valid_idx['paper'])]
y_test=y.iloc[test_idx['paper']]
from xgboost import XGBClassifier

bst = XGBClassifier(n_estimators=100, max_depth=3, learning_rate=0.1)
bst.fit(X_train,y_train)
y_pred=bst.predict(X_test)
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100,"%")

KeyboardInterrupt: 