In [1]:
import pandas as pd
import os
import re
data_dir = os.path.expanduser("/Users/joshem/PhD Research/Data/pubmed-diabetes/data")

feature_names = ["w_{}".format(ii) for ii in range(500)]
column_names = ["ID"]+["Label"]+["subject"]+ feature_names 
node_data = pd.read_csv(os.path.join(data_dir, "Pubmed-Diabetes.NODE.paper.tab"), sep='\t|\=', header=None, names=column_names)
node_data.head(10)

/var/folders/k8/fv2pzvcn5p77dgds_c16lsl80000gn/T/ipykernel_7737/4033711607.py:8: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  node_data = pd.read_csv(os.path.join(data_dir, "Pubmed-Diabetes.NODE.paper.tab"), sep='\t|\=', header=None, names=column_names)


ID         Label            subject                   w_0  \
0       cat  1,2,3  label  numeric:w-rat:0.0  numeric:w-common:0.0   
1  12187484         label                  1                 w-rat   
2   2344352         label                  1                 w-rat   
3  14654069         label                  1                 w-rat   
4  16443886         label                  2               w-model   
5   2684155         label                  1                 w-rat   
6  15032912         label                  1                 w-rat   
7  17988185         label                  3                 w-use   
8   9834350         label                  3                   w-2   
9  16230722         label                  3              w-common   

                    w_1                   w_2                        w_3  \
0     numeric:w-use:0.0  numeric:w-examin:0.0  numeric:w-pathogenesi:0.0   
1   0.09393489570187145              w-common       0.028698458467273157   
2  0.023617916633613394                 w-use       0.014784159060186597   
3   0.10226314418677966                 w-use       0.010668980765083111   
4  0.038714646134547365             w-develop       0.014074824697725849   
5  0.030615817858387732                w-anim        0.08017901011192922   
6   0.11689675909566226               w-studi       0.005201366066481255   
7  0.007445259958367352               w-studi        0.01111371022838081   
8  0.006157469794431223              w-compar         0.0318839384719277   
9  0.010479105166473187                 w-use      0.0042941540838716255   

                         w_4                   w_5                  w_6  ...  \
0  numeric:w-retinopathi:0.0    numeric:w-mous:0.0  numeric:w-studi:0.0  ...   
1                      w-use   0.01176012652514843             w-examin  ...   
2                     w-anim  0.030926189614601272            w-metabol  ...   
3                     w-anim   0.04463573758808431          w-contribut  ...   
4                    w-month  0.023996179817274765             w-method  ...   
5                   w-compar  0.019287814631166137             w-normal  ...   
6                  w-metabol  0.018465876498282723                  w-2  ...   
7                    w-model  0.013229825117920863                  w-2  ...   
8                        w-6  0.026709793561887893              w-level  ...   
9                    w-studi  0.004273321498602856                  w-2  ...   

                   w_490                   w_491               w_492  \
0  numeric:w-urinari:0.0  numeric:w-myocardi:0.0  numeric:w-meal:0.0   
1                   None                    None                None   
2                   None                    None                None   
3                   None                    None                None   
4                   None                    None                None   
5                   None                    None                None   
6                   None                    None                None   
7                   None                    None                None   
8                   None                    None                None   
9                   None                    None                None   

               w_493                w_494                w_495  \
0  numeric:w-ica:0.0  numeric:w-locus:0.0  numeric:w-tcell:0.0   
1               None                 None                 None   
2               None                 None                 None   
3               None                 None                 None   
4               None                 None                 None   
5               None                 None                 None   
6               None                 None                 None   
7               None                 None                 None   
8               None                 None                 None   
9               None                 None                 None   



In [2]:
import numpy as np
DataS = node_data.drop(labels=0, axis=0)
DataS = DataS.fillna(value=np.nan)
DataS.head()

ID  Label subject      w_0                   w_1        w_2  \
1  12187484  label       1    w-rat   0.09393489570187145   w-common   
2   2344352  label       1    w-rat  0.023617916633613394      w-use   
3  14654069  label       1    w-rat   0.10226314418677966      w-use   
4  16443886  label       2  w-model  0.038714646134547365  w-develop   
5   2684155  label       1    w-rat  0.030615817858387732     w-anim   

                    w_3       w_4                   w_5          w_6  ...  \
1  0.028698458467273157     w-use   0.01176012652514843     w-examin  ...   
2  0.014784159060186597    w-anim  0.030926189614601272    w-metabol  ...   
3  0.010668980765083111    w-anim   0.04463573758808431  w-contribut  ...   
4  0.014074824697725849   w-month  0.023996179817274765     w-method  ...   
5   0.08017901011192922  w-compar  0.019287814631166137     w-normal  ...   

  w_490 w_491 w_492 w_493 w_494 w_495 w_496 w_497 w_498 w_499  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[5 rows x 503 columns]

In [3]:
DataS=DataS.replace({'subject': {'1':0 , '2': 1,'3':2}})
# label 1=0 
#		label 2= 1
#		label 3=2


DataS.head()

ID  Label  subject      w_0                   w_1        w_2  \
1  12187484  label        0    w-rat   0.09393489570187145   w-common   
2   2344352  label        0    w-rat  0.023617916633613394      w-use   
3  14654069  label        0    w-rat   0.10226314418677966      w-use   
4  16443886  label        1  w-model  0.038714646134547365  w-develop   
5   2684155  label        0    w-rat  0.030615817858387732     w-anim   

                    w_3       w_4                   w_5          w_6  ...  \
1  0.028698458467273157     w-use   0.01176012652514843     w-examin  ...   
2  0.014784159060186597    w-anim  0.030926189614601272    w-metabol  ...   
3  0.010668980765083111    w-anim   0.04463573758808431  w-contribut  ...   
4  0.014074824697725849   w-month  0.023996179817274765     w-method  ...   
5   0.08017901011192922  w-compar  0.019287814631166137     w-normal  ...   

  w_490 w_491 w_492 w_493 w_494 w_495 w_496 w_497 w_498 w_499  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[5 rows x 503 columns]

In [19]:
from natsort import index_natsorted, order_by_index

Data = DataS.reindex(index=order_by_index(DataS.index, index_natsorted(DataS['ID'], reverse=False)))
Data.head()

ID  Label  subject      w_0                   w_1       w_2  \
12588   7145  label        0    w-rat   0.14376123168286414  w-examin   
19548  29094  label        0    w-rat   0.09538004794343873     w-use   
13217  34420  label        0    w-rat   0.11323658659951627    w-anim   
10330  34548  label        0  w-studi  0.007356217722594917    w-anim   
13972  37920  label        0    w-rat    0.1377711803627448   w-studi   

                        w_3       w_4                   w_5         w_6  ...  \
12588  0.024710673888640275   w-studi  0.007462829573647018   w-metabol  ...   
19548   0.01990175258102042  w-compar  0.020029653655441758         w-6  ...   
13217   0.05931050063074217       w-2  0.008266192326770682    w-obtain  ...   
10330  0.030926189614601272    w-mice    0.1523641186469851   w-increas  ...   
13972   0.01430375668282345    w-anim  0.060134257583946915  w-investig  ...   

      w_490 w_491 w_492 w_493 w_494 w_495 w_496 w_497 w_498 w_499  
12588   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
19548   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
13217   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
10330   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
13972   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[5 rows x 503 columns]

In [5]:
f=node_data.loc[0, feature_names].values.flatten().tolist()
f.insert(0,'numeric:w-rat:0.0')
f.remove('string:summary')
#print(f)
word=[]
for x in f:
    x=x.replace("numeric:","")
    x=x.replace(":0.0","")
    word.append(x)
#print(word)    
print(len(word))

500


In [6]:
IdS=list(DataS['ID'].to_numpy())
Id=list(Data['ID'].to_numpy())
Index=[]
for s in Id:
    Index.append(IdS.index(s)+1)
print(len(Index))
Fec=[]
for i in range(19717):
    vec=[]
    f=Data.loc[Index[i], feature_names].values.flatten().tolist()
    target_ibdex = f.index('summary')
    d=f[:target_ibdex]
    for z in word:
        if z in d:
            vec.append(d[d.index(z)+1])
        else:
            vec.append(0)
    f.clear()
    Fec.append(vec)
#print(Fec)
df = pd.DataFrame(Fec, columns =word) 
df.insert(loc=500,column='subject',value=Data['subject'].to_numpy())
df.head()

19717


w-rat w-common                w-use              w-examin  \
0  0.14376123168286414        0                    0  0.024710673888640275   
1  0.09538004794343873        0  0.01990175258102042                     0   
2  0.11323658659951627        0                    0                     0   
3                    0        0                    0                     0   
4   0.1377711803627448        0                    0                     0   

  w-pathogenesi w-retinopathi w-mous               w-studi  \
0             0             0      0  0.007462829573647018   
1             0             0      0                     0   
2             0             0      0                     0   
3             0             0      0  0.007356217722594917   
4             0             0      0   0.01430375668282345   

                 w-anim w-model  ... w-urinari w-myocardi w-meal w-ica  \
0                     0       0  ...         0          0      0     0   
1                     0       0  ...         0          0      0     0   
2   0.05931050063074217       0  ...         0          0      0     0   
3  0.030926189614601272       0  ...         0          0      0     0   
4  0.060134257583946915       0  ...         0          0      0     0   

  w-locus w-tcell w-depress w-bone w-mutat subject  
0       0       0         0      0       0       0  
1       0       0         0      0       0       0  
2       0       0         0      0       0       0  
3       0       0         0      0       0       0  
4       0       0         0      0       0       0  

[5 rows x 501 columns]

In [7]:
# import all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [10]:
# Scale data before applying PCA
scaling=StandardScaler()
 
# Use fit and transform method
scaling.fit(df)
Scaled_data=scaling.transform(df)
 
# Set the n_components=3
m=100
principal=PCA(n_components=m)
principal.fit(Scaled_data)
x=principal.transform(Scaled_data)
 
# Check the dimensions of data after PCA
print(x.shape)

(19717, 100)


In [20]:
feature_names=[]
for i in range(m):
    feature_names.append("P_{}".format(i))
Data1 = pd.DataFrame(x,columns=feature_names)
Data1.head()

P_0       P_1       P_2       P_3       P_4       P_5       P_6  \
0  3.090214 -4.847239  0.193572 -3.207573  1.087982 -0.071215 -2.224381   
1  2.211296 -4.923648  0.599147 -1.926494  0.326379  1.058527 -0.509812   
2  2.197296 -3.762209  1.565758 -2.387267 -1.112244  1.379524 -0.725761   
3 -0.276116 -4.033687 -2.449679 -0.500841  0.406654 -0.027509 -0.686953   
4  3.647518 -4.323798  0.766677 -2.646270  1.763910  1.449773  0.177784   

        P_7       P_8       P_9  ...      P_90      P_91      P_92      P_93  \
0 -0.495039  0.043627 -1.872733  ...  0.441003  0.972997 -0.300148  1.859048   
1  1.432746  0.185357 -0.983894  ... -1.436338  0.582109 -1.931186  0.913441   
2  2.423092 -3.055501  3.756130  ...  1.234867  2.948328  1.017219 -0.239450   
3 -0.707279 -0.874329 -0.764888  ... -0.406556 -0.942915  0.918238 -0.249517   
4  1.139419 -0.923977 -0.203424  ...  0.891555 -0.065545 -1.519143  0.800503   

       P_94      P_95      P_96      P_97      P_98      P_99  
0  1.138610 -0.377535  0.595494 -2.112290  0.361505 -1.331763  
1 -0.531743 -0.519045  0.446280 -0.247543  0.681103 -0.218289  
2  0.136509  0.954241 -0.033677  3.458602  1.476904 -0.887068  
3 -0.908400 -0.489690  0.236835 -0.592116  0.661572  0.911285  
4 -1.466113  1.577265  1.003261 -1.756168  1.420241 -1.384442  

[5 rows x 100 columns]

In [15]:
a=[2,3,4]
import statistics
statistics.mean(a)
statistics.stdev(a)

1.0

In [17]:
p_data = open("/Users/joshem/PhD Research/Data/pubmed-diabetes/data/Pubmed-Diabetes.DIRECTED.cites.tab")


# Create a list from the data
myls=list(p_data)

# Remove the new line symbole from the list
mylist = [line.rstrip('\n') for line in myls]
#print(mylist)
#print(graph_ind)
#print(graph_level)

p_data.close()
mynode=[]
Node=[]
i=0
for d in mylist:
    d=mylist[i].split("\t")
    mynode.append(d[1])
    Node.append(d[0])
    mynode.append(d[3])
    i=i+1
#print(mynode)
node_ID1=np.unique(mynode)
node_ID2=list(node_ID1)
#print(node_ID2)
n=len(node_ID2)

In [22]:
from natsort import natsorted, ns
node_ID=natsorted(node_ID2)
#print(node_ID)

A=np.zeros((n,n))
i=0
for d in mylist:
    d=mylist[i].split("\t")
    A[node_ID.index(d[1])][node_ID.index(d[3])]=1
    i=i+1;
print(" The adjacency Matrix")
print("=======================")
print(A)

catagories=Data['subject'].to_numpy()
print(catagories)


 The adjacency Matrix
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0 0 0 ... 1 2 2]


In [29]:
D_only=[]
S_only=[]
Both=[]

In [55]:
import random
p=random.sample(range(19717), 1000)
#print(p)
q=[]
for i in range(n):
    if i not in p:
        q.append(i)

class_60=np.array(catagories)
for d in p:
    class_60[d]=3
print(class_60)
for i in range(n):
    A[i][i]=class_60[i]
print(A)

[0 0 0 ... 1 2 2]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 0. ... 0. 0. 2.]]


In [56]:
def CountX(lst,x):
    return(lst.count(x))

Node_class=[0,1,2,3]
F_vec=[]
for i in range(n):
    node_F=[]
    list_out=[]
    list_In=[]
    S_nbd_out=[]
    S_nbd_in=[]
    for j in range(n):
        if A[i][j]==1 and i!=j:
            list_out.append(A[j][j])
            for k in range(n):
                if A[j][k]==1 and k!=j:
                    S_nbd_out.append(A[k][k])
        if A[j][i]==1 and i!=j:
            list_In.append(A[j][j])
            for k in range(n):
                if A[k][j]==1 and k!=j:
                    S_nbd_in.append(A[k][k])
                
    for d in Node_class:

        node_F.append(CountX(list_out,d))
        node_F.append(CountX(list_In,d))
    for d in Node_class:
        node_F.append(CountX(S_nbd_out,d))
        node_F.append(CountX(S_nbd_in,d))
    F_vec.append(node_F)

In [57]:
x =np.array(F_vec)
k=16

feature=["a_0","b_0"]
for i in range(1,k-1,2):
    feature.append("a_{}".format(int((i+1)/2)))
    feature.append("b_{}".format(int((i+1)/2)))
data = pd.DataFrame(x,columns=feature)
data.insert(loc=k,column='Class',value=Data['subject'].to_numpy())
data.head()

a_0  b_0  a_1  b_1  a_2  b_2  a_3  b_3  a_4  b_4  a_5  b_5  a_6  b_6  a_7  \
0    0    2    0    0    0    0    0    0    0    0    0    0    0    0    0   
1    0    4    0    0    0    0    0    0    0    4    0    0    0    0    0   
2    0    0    0    0    0    0    0    1    0    1    0    0    0    0    0   
3    0    1    0    0    0    0    0    0    0    5    0    1    0    0    0   
4    0    1    0    1    0    0    0    0    0    0    0    3    0    0    0   

   b_7  Class  
0    0      0  
1    0      0  
2    0      0  
3    0      0  
4    0      0

In [58]:
result = pd.concat([Data1,data], axis=1)
result.head()

P_0       P_1       P_2       P_3       P_4       P_5       P_6  \
0  3.090214 -4.847239  0.193572 -3.207573  1.087982 -0.071215 -2.224381   
1  2.211296 -4.923648  0.599147 -1.926494  0.326379  1.058527 -0.509812   
2  2.197296 -3.762209  1.565758 -2.387267 -1.112244  1.379524 -0.725761   
3 -0.276116 -4.033687 -2.449679 -0.500841  0.406654 -0.027509 -0.686953   
4  3.647518 -4.323798  0.766677 -2.646270  1.763910  1.449773  0.177784   

        P_7       P_8       P_9  ...  b_3  a_4  b_4  a_5  b_5  a_6  b_6  a_7  \
0 -0.495039  0.043627 -1.872733  ...    0    0    0    0    0    0    0    0   
1  1.432746  0.185357 -0.983894  ...    0    0    4    0    0    0    0    0   
2  2.423092 -3.055501  3.756130  ...    1    0    1    0    0    0    0    0   
3 -0.707279 -0.874329 -0.764888  ...    0    0    5    0    1    0    0    0   
4  1.139419 -0.923977 -0.203424  ...    0    0    0    0    3    0    0    0   

   b_7  Class  
0    0      0  
1    0      0  
2    0      0  
3    0      0  
4    0      0  

[5 rows x 117 columns]

In [59]:
k=16
feature=["a_0","b_0"]
for i in range(1,k-1,2):
    feature.append("a_{}".format(int((i+1)/2)))
    feature.append("b_{}".format(int((i+1)/2)))
l=50
for i in range(l):
    feature.append("P_{}".format(i))

    
    
X=result[feature] # Features
y=result['Class']  # Labels
X_train=X.iloc[q]
X_test=X.iloc[p]
y_train=y.iloc[q]
y_test=y.iloc[p]

from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(X_train)  
X_train = scaler.transform(X_train)  
# apply same transformation to test data
X_test = scaler.transform(X_test)  

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(700,), random_state=1,max_iter=10000, warm_start=True)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100,"%")
Both.append(metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 90.4 %


In [30]:
Both.append(metrics.accuracy_score(y_test, y_pred)*100)

In [60]:
k=16
feature=["a_0","b_0"]
for i in range(1,k-1,2):
    feature.append("a_{}".format(int((i+1)/2)))
    feature.append("b_{}".format(int((i+1)/2)))
#l=50
#for i in range(l):
#    feature.append("P_{}".format(i))

    
    
X=result[feature] # Features
y=result['Class']  # Labels
X_train=X.iloc[q]
X_test=X.iloc[p]
y_train=y.iloc[q]
y_test=y.iloc[p]

from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(X_train)  
X_train = scaler.transform(X_train)  
# apply same transformation to test data
X_test = scaler.transform(X_test)  

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(700,), random_state=1,max_iter=10000, warm_start=True)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100,"%")
S_only.append(metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 83.3 %


In [61]:
#k=16
#feature=["a_0","b_0"]
#for i in range(1,k-1,2):
#    feature.append("a_{}".format(int((i+1)/2)))
#    feature.append("b_{}".format(int((i+1)/2)))
l=100
for i in range(l):
    feature.append("P_{}".format(i))

    
    
X=result[feature] # Features
y=result['Class']  # Labels
X_train=X.iloc[q]
X_test=X.iloc[p]
y_train=y.iloc[q]
y_test=y.iloc[p]

from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(X_train)  
X_train = scaler.transform(X_train)  
# apply same transformation to test data
X_test = scaler.transform(X_test)  

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(700,), random_state=1,max_iter=10000, warm_start=True)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred)*100,"%")
D_only.append(metrics.accuracy_score(y_test, y_pred)*100)

Accuracy: 93.10000000000001 %


In [67]:
print(statistics.mean(Both))
print(statistics.stdev(Both))
print(statistics.mean(S_only))
print(statistics.stdev(S_only))
print(statistics.mean(D_only))
print(statistics.stdev(D_only))

90.425
0.6344288770224753
81.575
1.1842719282326968
91.72500000000001
1.6700798384109317
